// Code generated by gen_cpp_commands.go; DO NOT EDIT.

#pragma once
#include <nlohmann/json.hpp>
#include <string>

struct CommandBase {
  virtual ~CommandBase() = default;
  virtual std::string command_name() const = 0;
  virtual nlohmann::json to_json() const = 0;
};

// MeasureCommand: issued to runtime to request a measurement from the
// instrument server
struct MeasureCommand : public CommandBase {
  static constexpr const char *NAME = "MEASURE_COMMAND";
  // When the response was completed
  int timestamp;
  // the measurement request to be taken
  std::string request;
  std::string command_name() const override { return NAME; }
  nlohmann::json to_json() const override {
    nlohmann::json j;
    j["request"] = request;
    j["timestamp"] = timestamp;
    return j;
  }
  static MeasureCommand from_json(const nlohmann::json &j) {
    MeasureCommand obj;
    if (j.contains("request"))
      j.at("request").get_to(obj.request);
    if (j.contains("timestamp"))
      j.at("timestamp").get_to(obj.timestamp);
    return obj;
  }
};

// MeasureResponse: Recieve a response from the runtime as to the measurement
// performed
struct MeasureResponse : public CommandBase {
  static constexpr const char *NAME = "MEASURE_RESPONSE";
  // the stream carrying all of the possible measurements
  std::string stream;
  // When the response was completed
  int timestamp;
  // the channel that the large measurement will appear on
  std::string channel;
  std::string command_name() const override { return NAME; }
  nlohmann::json to_json() const override {
    nlohmann::json j;
    j["channel"] = channel;
    j["stream"] = stream;
    j["timestamp"] = timestamp;
    return j;
  }
  static MeasureResponse from_json(const nlohmann::json &j) {
    MeasureResponse obj;
    if (j.contains("channel"))
      j.at("channel").get_to(obj.channel);
    if (j.contains("stream"))
      j.at("stream").get_to(obj.stream);
    if (j.contains("timestamp"))
      j.at("timestamp").get_to(obj.timestamp);
    return obj;
  }
};

// StateRequest: Request the state of the device voltages on the sample
struct StateRequest : public CommandBase {
  static constexpr const char *NAME = "STATE_REQUEST";
  // When the response was completed
  int timestamp;
  std::string command_name() const override { return NAME; }
  nlohmann::json to_json() const override {
    nlohmann::json j;
    j["timestamp"] = timestamp;
    return j;
  }
  static StateRequest from_json(const nlohmann::json &j) {
    StateRequest obj;
    if (j.contains("timestamp"))
      j.at("timestamp").get_to(obj.timestamp);
    return obj;
  }
};

// StateResponse: The state of all the device voltages on the sample
struct StateResponse : public CommandBase {
  static constexpr const char *NAME = "STATE_RESPONSE";
  // the device voltage response
  std::string response;
  // When the response was completed
  int timestamp;
  std::string command_name() const override { return NAME; }
  nlohmann::json to_json() const override {
    nlohmann::json j;
    j["response"] = response;
    j["timestamp"] = timestamp;
    return j;
  }
  static StateResponse from_json(const nlohmann::json &j) {
    StateResponse obj;
    if (j.contains("response"))
      j.at("response").get_to(obj.response);
    if (j.contains("timestamp"))
      j.at("timestamp").get_to(obj.timestamp);
    return obj;
  }
};

// PortRequest: Request all current instrument ports
struct PortRequest : public CommandBase {
  static constexpr const char *NAME = "PORT_REQUEST";
  // When the response was completed
  int timestamp;
  std::string command_name() const override { return NAME; }
  nlohmann::json to_json() const override {
    nlohmann::json j;
    j["timestamp"] = timestamp;
    return j;
  }
  static PortRequest from_json(const nlohmann::json &j) {
    PortRequest obj;
    if (j.contains("timestamp"))
      j.at("timestamp").get_to(obj.timestamp);
    return obj;
  }
};

// PortPayload: All of the current instrument ports
struct PortPayload : public CommandBase {
  static constexpr const char *NAME = "PORT_PAYLOAD";
  // All of the knobs attached to the instrument server
  std::string knobs;
  // All of the meters attached to the instrument server
  std::string meters;
  // When the response was completed
  int timestamp;
  std::string command_name() const override { return NAME; }
  nlohmann::json to_json() const override {
    nlohmann::json j;
    j["meters"] = meters;
    j["timestamp"] = timestamp;
    j["knobs"] = knobs;
    return j;
  }
  static PortPayload from_json(const nlohmann::json &j) {
    PortPayload obj;
    if (j.contains("knobs"))
      j.at("knobs").get_to(obj.knobs);
    if (j.contains("meters"))
      j.at("meters").get_to(obj.meters);
    if (j.contains("timestamp"))
      j.at("timestamp").get_to(obj.timestamp);
    return obj;
  }
};

// DeviceConfigRequest: A request for the device configuration
struct DeviceConfigRequest : public CommandBase {
  static constexpr const char *NAME = "DEVICE_CONFIG_REQUEST";
  // When the response was completed
  int timestamp;
  std::string command_name() const override { return NAME; }
  nlohmann::json to_json() const override {
    nlohmann::json j;
    j["timestamp"] = timestamp;
    return j;
  }
  static DeviceConfigRequest from_json(const nlohmann::json &j) {
    DeviceConfigRequest obj;
    if (j.contains("timestamp"))
      j.at("timestamp").get_to(obj.timestamp);
    return obj;
  }
};

// DeviceConfigResponse: A response containing the device configuration
struct DeviceConfigResponse : public CommandBase {
  static constexpr const char *NAME = "DEVICE_CONFIG_RESPONSE";
  // The device config for use understanding the device layout
  std::string response;
  // When the response was completed
  int timestamp;
  std::string command_name() const override { return NAME; }
  nlohmann::json to_json() const override {
    nlohmann::json j;
    j["response"] = response;
    j["timestamp"] = timestamp;
    return j;
  }
  static DeviceConfigResponse from_json(const nlohmann::json &j) {
    DeviceConfigResponse obj;
    if (j.contains("response"))
      j.at("response").get_to(obj.response);
    if (j.contains("timestamp"))
      j.at("timestamp").get_to(obj.timestamp);
    return obj;
  }
};
