#include "falcon-autotuner/FalconParser.hpp"
#include <algorithm>
#include <fmt/core.h>
#include <regex>
#include <set>
#include <sstream>

namespace falcon::autotuner::dsl {

FalconCodeGenerator::GeneratedCode FalconCodeGenerator::generate(
    const std::vector<std::unique_ptr<AutotunerDecl>> &ast) {

  GeneratedCode code;

  std::ostringstream header;
  std::ostringstream source;

  // Generate header preamble
  header << "// GENERATED CODE - DO NOT EDIT\n";
  header << "// Generated by Falcon Autotuner Compiler\n\n";
  header << "#pragma once\n\n";
  header << "#include \"falcon-autotuner/Autotuner.hpp\"\n";
  header << "#include \"falcon-autotuner/MeasurementRoutine.hpp\"\n";
  header << "#include <memory>\n";
  header << "#include <functional>\n\n";

  header << "#ifdef _WIN32\n";
  header << "#  define FALCON_EXPORT __declspec(dllexport)\n";
  header << "#else\n";
  header
      << "#  define FALCON_EXPORT __attribute__((visibility(\"default\")))\n";
  header << "#endif\n\n";

  // Generate source preamble
  source << "// GENERATED CODE - DO NOT EDIT\n";
  source << "#include \"GeneratedAutotuners.hpp\"\n";
  source << "#include <stdexcept>\n";
  source << "#include <iostream>\n";
  source << "#include <cmath>\n\n";

  header << "namespace falcon {\n";
  header << "namespace autotuner {\n";
  header << "namespace generated {\n\n";

  source << "namespace falcon {\n";
  source << "namespace autotuner {\n";
  source << "namespace generated {\n\n";

  // Helper: condition evaluator
  source << "// Helper function to evaluate conditions\n";
  source << "bool eval_condition(const ParameterMap& params, const "
            "std::string& expr) {\n";
  source << "  // Simplified condition evaluator\n";
  source << "  // In production, use a proper expression parser\n";
  source << "  if (expr == \"true\") return true;\n";
  source << "  if (expr == \"false\") return false;\n";
  source << "  // TODO: Implement full expression evaluation\n";
  source << "  return true;\n";
  source << "}\n\n";

  // Wrapper for measurements that return ParameterMap
  source << "// Wrapper for ParameterMap-returning measurements\n";
  source << "class ParameterMapMeasurement : public MeasurementRoutine {\n";
  source << "public:\n";
  source
      << "  using Func = std::function<ParameterMap(const ParameterMap&)>;\n\n";
  source << "  ParameterMapMeasurement(std::string name, Func func)\n";
  source << "    : name_(std::move(name)), func_(std::move(func)) {}\n\n";
  source
      << "  MeasurementResult execute(const ParameterMap& inputs) override {\n";
  source << "    MeasurementResult result;\n";
  source << "    try {\n";
  source << "      auto outputs = func_(inputs);\n";
  source << "      result.outputs = outputs;\n";
  source << "      result.success = true;\n";
  source << "    } catch (const std::exception& e) {\n";
  source << "      result.success = false;\n";
  source << "      result.error_message = e.what();\n";
  source << "    }\n";
  source << "    return result;\n";
  source << "  }\n\n";
  source << "  std::string name() const override { return name_; }\n\n";
  source << "private:\n";
  source << "  std::string name_;\n";
  source << "  Func func_;\n";
  source << "};\n\n";

  // Generate code for each autotuner
  for (const auto &autotuner : ast) {
    generate_autotuner_builder(*autotuner, header, source, code);
  }

  // Registry function
  header << "\n/**\n";
  header << " * @brief Register all generated autotuners\n";
  header << " */\n";
  header << "void register_all_autotuners();\n\n";

  source << "void register_all_autotuners() {\n";
  source << "  auto& registry = AutotunerRegistry::instance();\n";
  for (const auto &autotuner : ast) {
    source << "  {\n";
    source << "    " << autotuner->name << "Builder builder;\n";
    source << "    registry.register_autotuner(builder.get_autotuner());\n";
    source << "  }\n";
  }
  source << "}\n\n";

  header << "} // namespace generated\n";
  header << "} // namespace autotuner\n";
  header << "} // namespace falcon\n";

  source << "} // namespace generated\n";
  source << "} // namespace autotuner\n";
  source << "} // namespace falcon\n";

  code.header_code = header.str();
  code.source_code = source.str();

  return code;
}

void FalconCodeGenerator::generate_autotuner_builder(
    const AutotunerDecl &autotuner, std::ostringstream &header,
    std::ostringstream &source, GeneratedCode &code) {

  std::string class_name = autotuner.name + "Builder";

  // Collect measurement functions
  std::set<std::string> measurements = extract_measurements(autotuner);
  for (const auto &meas : measurements) {
    code.required_measurements.push_back(autotuner.name + "::" + meas);
  }

  // Header declaration
  header << "/**\n";
  header << " * @brief Builder for " << autotuner.name << " autotuner\n";
  header << " */\n";
  header << "class " << class_name << " {\n";
  header << "public:\n";
  header << "  " << class_name << "();\n";
  header << "  std::shared_ptr<Autotuner> get_autotuner() const { return "
            "autotuner_; }\n";
  header << "private:\n";
  header << "  void build_state_machine();\n";
  header << "  std::shared_ptr<Autotuner> autotuner_;\n";
  header << "};\n\n";

  // Source implementation
  source << "// ============================================\n";
  source << "// " << autotuner.name << " Implementation\n";
  source << "// ============================================\n\n";

  source << class_name << "::" << class_name << "() {\n";
  source << "  autotuner_ = std::make_shared<Autotuner>(\"" << autotuner.name
         << "\");\n";
  source << "  build_state_machine();\n";
  source << "}\n\n";

  source << "void " << class_name << "::build_state_machine() {\n";

  // Collect all state names
  std::set<std::string> state_names = collect_state_names(autotuner);

  source << "  // Create all states\n";
  for (const auto &name : state_names) {
    source << "  auto state_" << sanitize_name(name)
           << " = autotuner_->create_state(\"" << name << "\");\n";
  }
  source << "\n";

  // Configure each state
  source << "  // Configure states and transitions\n";
  for (const auto &stmt : autotuner.statements) {
    generate_statement(*stmt, autotuner, source);
  }

  // Set entry state
  if (!autotuner.entry_state.empty()) {
    source << "\n  // Set entry state\n";
    source << "  autotuner_->set_entry_state(\"" << autotuner.entry_state
           << "\");\n";
  }

  source << "}\n\n";
}

void FalconCodeGenerator::generate_statement(const ASTNode &stmt,
                                             const AutotunerDecl &autotuner,
                                             std::ostringstream &source) {

  if (auto *state = dynamic_cast<const StateDecl *>(&stmt)) {
    generate_state_config(*state, autotuner, source);
  } else if (auto *for_loop = dynamic_cast<const ForLoop *>(&stmt)) {
    generate_for_loop(*for_loop, source);
  } else if (auto *while_loop = dynamic_cast<const WhileLoop *>(&stmt)) {
    generate_while_loop(*while_loop, source);
  }
}

void FalconCodeGenerator::generate_state_config(const StateDecl &state,
                                                const AutotunerDecl &autotuner,
                                                std::ostringstream &source) {

  std::string state_var = "state_" + sanitize_name(state.name);

  source << "  // State: " << state.name << "\n";

  // Set measurement if present
  if (!state.measurement_call.empty()) {
    source << "  " << state_var << "->set_measurement(\n";
    source << "    std::make_shared<ParameterMapMeasurement>(\n";
    source << "      \"" << state.measurement_call << "\",\n";
    source << "      [](const ParameterMap& inputs) {\n";
    source << "        return " << autotuner.name
           << "::" << state.measurement_call << "(inputs);\n";
    source << "      }\n";
    source << "    )\n";
    source << "  );\n";
  }

  // Generate transitions
  for (const auto &trans_node : state.transitions) {
    if (auto *trans =
            dynamic_cast<const ConditionalTransition *>(trans_node.get())) {
      generate_transition_with_transfer(*trans, state_var, autotuner, source);
    }
  }

  source << "\n";
}

void FalconCodeGenerator::generate_transition_with_transfer(
    const ConditionalTransition &trans, const std::string &state_var,
    const AutotunerDecl &autotuner, std::ostringstream &source) {

  // Parse transition: target_state[var1:mapped1, var2]
  std::string target = trans.target_state;
  std::map<std::string, std::string> var_mapping;

  size_t bracket_pos = target.find('[');
  if (bracket_pos != std::string::npos) {
    std::string base_target = target.substr(0, bracket_pos);
    std::string mappings = target.substr(bracket_pos + 1);

    // Remove trailing ]
    if (!mappings.empty() && mappings.back() == ']') {
      mappings.pop_back();
    }

    // Parse mappings: var1:mapped1, var2
    std::istringstream iss(mappings);
    std::string pair;
    while (std::getline(iss, pair, ',')) {
      size_t colon = pair.find(':');
      if (colon != std::string::npos) {
        std::string from = trim(pair.substr(0, colon));
        std::string to = trim(pair.substr(colon + 1));
        var_mapping[from] = to;
      } else {
        // Just variable name - transfer with same name
        std::string var = trim(pair);
        if (!var.empty()) {
          var_mapping[var] = var;
        }
      }
    }

    target = base_target;
  }

  // Parse cross-autotuner reference
  std::string target_autotuner = autotuner.name;
  std::string target_state = target;

  size_t double_colon = target.find("::");
  if (double_colon != std::string::npos) {
    target_autotuner = target.substr(0, double_colon);
    target_state = target.substr(double_colon + 2);
  }

  // Generate transition
  source << "  " << state_var << "->add_transition(StateTransition(\n";
  source << "    StateId(\"" << target_autotuner << "\", \"" << target_state
         << "\"),\n";
  source << "    TransitionCondition(\n";
  source << "      [](const ParameterMap& params) {\n";

  // Generate condition code
  if (trans.condition == "true") {
    source << "        return true;\n";
  } else if (trans.condition == "false") {
    source << "        return false;\n";
  } else {
    // Parse and generate condition
    std::string cond = trans.condition;

    // Simple replacements for common patterns
    // Replace "==" with proper comparison
    // This is simplified - a production compiler would parse properly
    source << "        // Condition: " << cond << "\n";
    source << "        return eval_condition(params, \"" << cond << "\");\n";
  }

  source << "      },\n";
  source << "      \"" << trans.condition << "\"\n";
  source << "    )\n";
  source << "  ));\n";

  // Note: Variable transfer would require extending StateTransition
  // For now, it's handled implicitly by ParameterMap merging
  if (!var_mapping.empty()) {
    source << "  // TODO: Variable transfer: ";
    for (const auto &[from, to] : var_mapping) {
      source << from;
      if (from != to) {
        source << " -> " << to;
      }
      source << " ";
    }
    source << "\n";
  }
}

void FalconCodeGenerator::generate_for_loop(const ForLoop &loop,
                                            std::ostringstream &source) {

  // Parse range expression: range(start, end, step)
  std::regex range_regex(R"(range\(([^,]+),([^,]+),([^)]+)\))");
  std::smatch match;

  if (std::regex_search(loop.iterable_expr, match, range_regex)) {
    std::string start = trim(match[1].str());
    std::string end = trim(match[2].str());
    std::string step = trim(match[3].str());

    source << "  // For loop: " << loop.variable << " in " << loop.iterable_expr
           << "\n";
    source << "  // Note: Loop expansion not fully implemented\n";
    source << "  // TODO: Expand states for range(" << start << ", " << end
           << ", " << step << ")\n\n";
  }
}

void FalconCodeGenerator::generate_while_loop(const WhileLoop &loop,
                                              std::ostringstream &source) {

  source << "  // While loop: " << loop.condition << "\n";
  source << "  // Note: While loops not supported in static generation\n\n";
}

std::string
FalconCodeGenerator::generate_condition_code(const std::string &condition) {
  if (condition == "true") {
    return "return true;";
  }
  if (condition == "false") {
    return "return false;";
  }

  // For now, use helper function
  return "return eval_condition(params, \"" + condition + "\");";
}

std::set<std::string>
FalconCodeGenerator::collect_state_names(const AutotunerDecl &autotuner) {

  std::set<std::string> names;

  for (const auto &stmt : autotuner.statements) {
    if (auto *state = dynamic_cast<const StateDecl *>(stmt.get())) {
      names.insert(state->name);
    } else if (auto *for_loop = dynamic_cast<const ForLoop *>(stmt.get())) {
      // For now, just add the body state names as-is
      // Full expansion would happen here
      for (const auto &body_state : for_loop->body_states) {
        names.insert(body_state->name);
      }
    }
  }

  return names;
}

std::set<std::string>
FalconCodeGenerator::extract_measurements(const AutotunerDecl &autotuner) {

  std::set<std::string> measurements;

  for (const auto &stmt : autotuner.statements) {
    if (auto *state = dynamic_cast<const StateDecl *>(stmt.get())) {
      if (!state->measurement_call.empty()) {
        // Extract function name (before parentheses)
        size_t paren_pos = state->measurement_call.find('(');
        std::string func_name =
            (paren_pos != std::string::npos)
                ? state->measurement_call.substr(0, paren_pos)
                : state->measurement_call;
        measurements.insert(func_name);
      }
    } else if (auto *for_loop = dynamic_cast<const ForLoop *>(stmt.get())) {
      for (const auto &body_state : for_loop->body_states) {
        if (!body_state->measurement_call.empty()) {
          size_t paren_pos = body_state->measurement_call.find('(');
          std::string func_name =
              (paren_pos != std::string::npos)
                  ? body_state->measurement_call.substr(0, paren_pos)
                  : body_state->measurement_call;
          measurements.insert(func_name);
        }
      }
    }
  }

  return measurements;
}

std::string FalconCodeGenerator::sanitize_name(const std::string &name) {
  std::string result = name;
  std::replace(result.begin(), result.end(), '-', '_');
  std::replace(result.begin(), result.end(), '.', '_');
  std::replace(result.begin(), result.end(), ':', '_');
  std::replace(result.begin(), result.end(), ' ', '_');
  return result;
}

std::string FalconCodeGenerator::trim(const std::string &str) {
  size_t first = str.find_first_not_of(" \t\n\r");
  if (first == std::string::npos)
    return "";
  size_t last = str.find_last_not_of(" \t\n\r");
  return str.substr(first, last - first + 1);
}

std::string
FalconCodeGenerator::substitute_variable(const std::string &text,
                                         const std::string &variable) {

  // Replace ${variable} with loop variable
  std::string result = text;
  std::string pattern = "${" + variable + "}";

  size_t pos = 0;
  while ((pos = result.find(pattern, pos)) != std::string::npos) {
    result.replace(pos, pattern.length(),
                   "\" + std::to_string(" + variable + ") + \"");
    pos += variable.length();
  }

  return result;
}

} // namespace falcon::autotuner::dsl
