#include "qarrayDevice/Device.hpp"

#include <cstdlib>
#include <memory>
#include <string>

#include <pybind11/embed.h>
#include <pybind11/numpy.h>
#include <pybind11/stl.h>

// Generated by cmake configure_file — contains FALCON_QARRAY_PYTHON_MODULE_DIR
// and FALCON_QARRAY_PYTHON_SITE_PACKAGES
#include "PythonModulePath.hpp"

namespace py = pybind11;
using namespace py::literals;

namespace falcon::qarray {

// ─────────────────────────────────────────────────────────────────────────────
// Interpreter singleton
// ─────────────────────────────────────────────────────────────────────────────
namespace {

struct InterpreterGuard {
  static InterpreterGuard &instance() {
    static InterpreterGuard guard;
    return guard;
  }

private:
  py::scoped_interpreter interp_;

  InterpreterGuard() : interp_() {
    // After the interpreter starts, immediately configure sys.path so that:
    //   1. qarray + numpy (in the venv site-packages) are importable
    //   2. device.py (in the install tree) is importable
    // We do this here, in the constructor, so it happens exactly once before
    // any module import is attempted.
    py::gil_scoped_acquire gil;
    auto sys = py::module_::import("sys");
    auto sys_path = sys.attr("path");

    // 1. Add venv site-packages (compile-time detected, or env var override)
    std::string site_packages;
    if (const char *env = std::getenv("FALCON_QARRAY_VENV_SITE_PACKAGES")) {
      site_packages = env;
    } else {
      site_packages = FALCON_QARRAY_PYTHON_SITE_PACKAGES;
    }
    if (!site_packages.empty()) {
      sys_path.attr("insert")(0, site_packages);
    }

    // 2. Add the device.py location
    std::string module_dir;
    if (const char *env = std::getenv("FALCON_QARRAY_PYTHON_PATH")) {
      module_dir = env;
    } else {
      module_dir = FALCON_QARRAY_PYTHON_MODULE_DIR;
    }
    if (!module_dir.empty()) {
      sys_path.attr("insert")(0, module_dir);
    }
  }
};

// Convert a numpy array to flat std::vector<double> + shape
std::pair<std::vector<double>, std::vector<int>>
numpy_to_vector(const py::object &arr) {
  auto np_arr = arr.cast<
      py::array_t<double, py::array::c_style | py::array::forcecast>>();
  auto buf = np_arr.request();

  std::vector<int> shape;
  shape.reserve(buf.ndim);
  for (py::ssize_t i = 0; i < buf.ndim; ++i) {
    shape.push_back(static_cast<int>(buf.shape[i]));
  }

  const double *ptr = static_cast<const double *>(buf.ptr);
  return {std::vector<double>(ptr, ptr + buf.size), shape};
}

std::pair<std::vector<double>, std::vector<int>>
numpy_int_to_double_vector(const py::object &arr) {
  py::object float_arr =
      py::module_::import("numpy").attr("array")(arr, "dtype"_a = "float64");
  return numpy_to_vector(float_arr);
}

} // anonymous namespace

// ─────────────────────────────────────────────────────────────────────────────
// Impl
// ─────────────────────────────────────────────────────────────────────────────
struct Device::Impl {
  py::object py_device;

  explicit Impl(const std::string &config_path) {
    // The caller is responsible for starting the interpreter via
    // pybind11::scoped_interpreter before constructing any Device.
    // We assert it's running here to give a clear error if not.
    if (Py_IsInitialized() == 0) {
      throw std::runtime_error("Python interpreter is not initialized. "
                               "Create a pybind11::scoped_interpreter before "
                               "constructing falcon::qarray::Device.");
    }

    py::gil_scoped_acquire gil;

    // Set up sys.path (site-packages + module dir) if not already done.
    // We use a flag so this only runs once per interpreter lifetime.
    static bool path_configured = false;
    if (!path_configured) {
      auto sys = py::module_::import("sys");
      auto sys_path = sys.attr("path");

      std::string site_packages;
      if (const char *env = std::getenv("FALCON_QARRAY_VENV_SITE_PACKAGES")) {
        site_packages = env;
      } else {
        site_packages = FALCON_QARRAY_PYTHON_SITE_PACKAGES;
      }
      if (!site_packages.empty()) {
        sys_path.attr("insert")(0, site_packages);
      }

      std::string module_dir;
      if (const char *env = std::getenv("FALCON_QARRAY_PYTHON_PATH")) {
        module_dir = env;
      } else {
        module_dir = FALCON_QARRAY_PYTHON_MODULE_DIR;
      }
      if (!module_dir.empty()) {
        sys_path.attr("insert")(0, module_dir);
      }

      path_configured = true;
    }

    py::module_ qd_module = py::module_::import("device");
    py::object DeviceClass = qd_module.attr("Device");
    py_device = DeviceClass(config_path);
  }
};

// ─────────────────────────────────────────────────────────────────────────────
// Device public API
// ─────────────────────────────────────────────────────────────────────────────

Device::Device(const std::string &config_path, bool accumulation_mode)
    : impl_(std::make_unique<Impl>(config_path)),
      accumulation_mode_(accumulation_mode) {}

Device Device::from_config_path(const std::string &yaml_path) {
  return Device(yaml_path);
}

Device::~Device() = default;
Device::Device(Device &&) noexcept = default;
Device &Device::operator=(Device &&) noexcept = default;

void Device::set_voltage(const std::string &gate_name, double value) {
  py::gil_scoped_acquire gil;
  double set_voltage = value;
  if (accumulation_mode_) {
    // In accumulation mode, set_voltage adds to the existing voltage
    set_voltage = -value;
  }
  impl_->py_device.attr("set_voltage")(gate_name, set_voltage);
}

void Device::set_voltages(const std::map<std::string, double> &voltage_dict) {
  py::gil_scoped_acquire gil;
  if (accumulation_mode_) {
    // In accumulation mode, set_voltages adds to the existing voltages
    std::map<std::string, double> adjusted_dict;
    for (const auto &[gate, voltage] : voltage_dict) {
      adjusted_dict[gate] = -voltage;
    }
    impl_->py_device.attr("set_voltages")(adjusted_dict);
    return;
  }
  impl_->py_device.attr("set_voltages")(voltage_dict);
}

int Device::n_dots() const {
  py::gil_scoped_acquire gil;
  return impl_->py_device.attr("n_dots").cast<int>();
}

std::vector<std::string> Device::gate_names() const {
  py::gil_scoped_acquire gil;
  return impl_->py_device.attr("gate_names").cast<std::vector<std::string>>();
}

std::map<std::string, double> Device::voltages() const {
  py::gil_scoped_acquire gil;
  if (accumulation_mode_) {
    // In accumulation mode, voltages() returns the accumulated voltages
    std::map<std::string, double> raw_voltages =
        impl_->py_device.attr("voltages").cast<std::map<std::string, double>>();
    std::map<std::string, double> adjusted_voltages;
    for (const auto &[gate, voltage] : raw_voltages) {
      adjusted_voltages[gate] = -voltage;
    }
    return adjusted_voltages;
  }
  return impl_->py_device.attr("voltages")
      .cast<std::map<std::string, double>>();
}

ScanResult2D Device::scan_2d(const std::string &x_gate,
                             const std::string &y_gate,
                             std::pair<double, double> x_range,
                             std::pair<double, double> y_range,
                             int resolution) {
  py::gil_scoped_acquire gil;
  std::pair<double, double> temp_x_range = x_range;
  std::pair<double, double> temp_y_range = y_range;
  if (accumulation_mode_) {
    // In accumulation mode, scan_2d returns the accumulated voltages
    temp_x_range = {-x_range.second, -x_range.first};
    temp_y_range = {-y_range.second, -y_range.first};
  }
  py::dict result = impl_->py_device.attr("scan_2d")(
      x_gate, y_gate, py::make_tuple(temp_x_range.first, temp_x_range.second),
      py::make_tuple(temp_y_range.first, temp_y_range.second), resolution);

  ScanResult2D out;
  out.x_gate = x_gate;
  out.y_gate = y_gate;
  out.x_range = x_range;
  out.y_range = y_range;
  out.resolution = resolution;

  auto [cs, cs_s] = numpy_int_to_double_vector(result["charge_states"]);
  out.charge_states = std::move(cs);
  out.charge_states_shape = std::move(cs_s);

  if (result.contains("sensor_output")) {
    out.has_sensor = true;
    auto [so, so_s] = numpy_to_vector(result["sensor_output"]);
    out.sensor_output = std::move(so);
    out.sensor_output_shape = std::move(so_s);
    auto [ds, ds_s] = numpy_to_vector(result["differentiated_signal"]);
    out.differentiated_signal = std::move(ds);
    out.differentiated_signal_shape = std::move(ds_s);
  }
  return out;
}

ScanResult1D Device::scan_1d(const std::string &gate,
                             std::pair<double, double> v_range,
                             int resolution) {
  py::gil_scoped_acquire gil;
  std::pair<double, double> temp_v_range = v_range;
  if (accumulation_mode_) {
    // In accumulation mode, scan_1d returns the accumulated voltages
    temp_v_range = {-v_range.second, -v_range.first};
  }
  py::dict result = impl_->py_device.attr("scan_1d")(
      gate, py::make_tuple(temp_v_range.first, temp_v_range.second),
      resolution);

  ScanResult1D out;
  out.gate = gate;
  out.v_range = v_range;
  out.resolution = resolution;

  auto [cs, cs_s] = numpy_int_to_double_vector(result["charge_states"]);
  out.charge_states = std::move(cs);
  out.charge_states_shape = std::move(cs_s);

  if (result.contains("sensor_output")) {
    out.has_sensor = true;
    auto [so, so_s] = numpy_to_vector(result["sensor_output"]);
    out.sensor_output = std::move(so);
    out.sensor_output_shape = std::move(so_s);
    auto [ds, ds_s] = numpy_to_vector(result["differentiated_signal"]);
    out.differentiated_signal = std::move(ds);
    out.differentiated_signal_shape = std::move(ds_s);
  }
  return out;
}

ScanResultRay Device::scan_ray(const std::map<std::string, double> &start,
                               const std::map<std::string, double> &end,
                               int resolution) {
  py::gil_scoped_acquire gil;
  std::map<std::string, double> temp_start = start;
  std::map<std::string, double> temp_end = end;
  if (accumulation_mode_) {
    // In accumulation mode, scan_ray returns the accumulated voltages
    for (const auto &[gate, voltage] : end) {
      temp_start[gate] = -voltage;
    }
    for (const auto &[gate, voltage] : start) {
      temp_end[gate] = -voltage;
    }
  }
  py::dict result =
      impl_->py_device.attr("scan_ray")(temp_start, temp_end, resolution);

  ScanResultRay out;
  out.start = start;
  out.end = end;
  out.resolution = resolution;

  auto [cs, cs_s] = numpy_int_to_double_vector(result["charge_states"]);
  out.charge_states = std::move(cs);
  out.charge_states_shape = std::move(cs_s);

  auto [traj, traj_s] = numpy_to_vector(result["trajectory"]);
  out.trajectory = std::move(traj);
  out.trajectory_shape = std::move(traj_s);

  if (result.contains("sensor_output")) {
    out.has_sensor = true;
    auto [so, so_s] = numpy_to_vector(result["sensor_output"]);
    out.sensor_output = std::move(so);
    out.sensor_output_shape = std::move(so_s);
    auto [ds, ds_s] = numpy_to_vector(result["differentiated_signal"]);
    out.differentiated_signal = std::move(ds);
    out.differentiated_signal_shape = std::move(ds_s);
  }
  return out;
}

} // namespace falcon::qarray
